import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect } from 'react'

export default function Home() {

  useEffect(() => {
    axios.get('https://rickandmortyapi.com/api/character').then(response => console.log(response))
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Rick & Morty Case</h1>
      </main>
    </div>
  )
}
